[versions]
agp = "9.2.1"
kotlin = "2.0.21"
r8_annotations = "v1.0.1"
androidvmtools = "b59db54b9d-SNAPSHOT"
kavarefCore = "1.0.1"
zygisk = "e985fbf57a-SNAPSHOT"
lsparanoid = "0.6.0"
browser = "1.9.0"
appcompat = "1.7.1"

activityCompose = "1.10.1"
composeBom = "2025.08.01"

xposedApi = "82"
uiToolingPreview = "1.9.0"
uiTooling = "1.9.0"
exifinterface = "1.4.2"
materialComponents = "1.14.0"

[libraries]
androidvmtools = { module = "io.github.vova7878:AndroidVMTools", version.ref = "androidvmtools" }
r8-annotations = { module = "io.github.vova7878:R8Annotations", version.ref = "r8_annotations" }
zygote-runtime = { module = "io.github.nightstars1.ZygoteLoader:runtime", version.ref = "zygisk" }
kavaref-core = { module = "com.highcapable.kavaref:kavaref-core", version.ref = "kavarefCore" }
kavaref-extension = { module = "com.highcapable.kavaref:kavaref-extension", version.ref = "kavarefCore" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityCompose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposedApi" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiToolingPreview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
material-components = { group = "com.google.android.material", name = "material", version.ref = "materialComponents" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
java-zygisk = { id = "io.github.nightstars1.ZygoteLoader", version.ref = "zygisk" }
lsparanoid = { id = "org.lsposed.lsparanoid", version.ref = "lsparanoid" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
