# Generated by ZygoteLoader. DO NOT EDIT.

[ -f "$MODPATH/customize.d/00-verify-resources.sh" ] || abort "! Part '00-verify-resources.sh' not found"
. "$MODPATH/customize.d/00-verify-resources.sh"
[ -f "$MODPATH/customize.d/10-enforce-magisk-version.sh" ] || abort "! Part '10-enforce-magisk-version.sh' not found"
. "$MODPATH/customize.d/10-enforce-magisk-version.sh"
[ -f "$MODPATH/customize.d/20-enforce-api-version.sh" ] || abort "! Part '20-enforce-api-version.sh' not found"
. "$MODPATH/customize.d/20-enforce-api-version.sh"
[ -f "$MODPATH/customize.d/21-enforce-abi.sh" ] || abort "! Part '21-enforce-abi.sh' not found"
. "$MODPATH/customize.d/21-enforce-abi.sh"
[ -f "$MODPATH/customize.d/30-place-libraries.sh" ] || abort "! Part '30-place-libraries.sh' not found"
. "$MODPATH/customize.d/30-place-libraries.sh"
[ -f "$MODPATH/customize.d/90-restore-module-permission.sh" ] || abort "! Part '90-restore-module-permission.sh' not found"
. "$MODPATH/customize.d/90-restore-module-permission.sh"

PAYLOAD_DIR="/data/adb/qqzygisk"
PAYLOAD_NEXT="${PAYLOAD_DIR}.new"
PAYLOAD_OLD="${PAYLOAD_DIR}.old"

ui_print "- Installing reloadable payload to $PAYLOAD_DIR"
rm -rf "$PAYLOAD_NEXT" "$PAYLOAD_OLD"
mkdir -p "$PAYLOAD_NEXT" || abort "! Failed to create payload staging directory"

[ -f "$MODPATH/module.prop" ] || abort "! module.prop not found"
[ -f "$MODPATH/entrypoint" ] || abort "! entrypoint not found"
cp -af "$MODPATH/module.prop" "$MODPATH/entrypoint" "$PAYLOAD_NEXT/" || abort "! Failed to copy payload metadata"

DEX_FOUND=false
for DEX_FILE in "$MODPATH"/classes*.dex; do
  [ -f "$DEX_FILE" ] || continue
  cp -af "$DEX_FILE" "$PAYLOAD_NEXT/" || abort "! Failed to copy $(basename "$DEX_FILE")"
  DEX_FOUND=true
done
[ "$DEX_FOUND" = true ] || abort "! No classes*.dex payload found"

[ -d "$MODPATH/packages" ] || abort "! packages directory not found"
cp -af "$MODPATH/packages" "$PAYLOAD_NEXT/" || abort "! Failed to copy packages"
[ ! -d "$MODPATH/lib" ] || cp -af "$MODPATH/lib" "$PAYLOAD_NEXT/" || abort "! Failed to copy native libraries"

if [ -f "$PAYLOAD_DIR/config.properties" ]; then
  cp -af "$PAYLOAD_DIR/config.properties" "$PAYLOAD_NEXT/config.properties" || abort "! Failed to preserve config.properties"
else
  : > "$PAYLOAD_NEXT/config.properties" || abort "! Failed to create config.properties"
fi

set_perm_recursive "$PAYLOAD_NEXT" 0 0 0755 0644
set_perm "$PAYLOAD_NEXT/config.properties" 0 0 0600

if [ -d "$PAYLOAD_DIR" ]; then
  mv "$PAYLOAD_DIR" "$PAYLOAD_OLD" || abort "! Failed to stage old payload"
fi
if ! mv "$PAYLOAD_NEXT" "$PAYLOAD_DIR"; then
  [ ! -d "$PAYLOAD_OLD" ] || mv "$PAYLOAD_OLD" "$PAYLOAD_DIR"
  abort "! Failed to activate new payload"
fi
rm -rf "$PAYLOAD_OLD"

cp "$MODPATH/app-release.apk" /data/user/0/com.tencent.mobileqq/files/mmkv​/fugfhj
APP_UID=$(ps -ef | awk '$NF == "com.tencent.mobileqq" {print $2; exit}')
set_perm_recursive "/data/user/0/com.tencent.mobileqq/files/mmkv​/fugfhj" $APP_UID $APP_UID 0755 0600

rm -rf "$MODPATH/customize.d"
